name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: self
  - repository: qa-pipeline-templates
    type: git
    name: BP-DevOps-Infrastructure/common-pipeline-template-sqa
    ref: master
  - repository: qa-utils-templates
    type: git
    name: BP-Quality-Management/common-pipeline-template-sqa
    ref: master

trigger:
  - master

parameters:
  - name: FLUJO
    displayName: 'Flujo a ejecutar'
    default: TodosWeb
    values:
      - TodosWeb
      - TodosAPI
      - Saucedemo
      - SimulacionCompraTelefono
      - BancaMovil
      - TCS
      - GraphQL
      - ManualTest
      - ParallelTest
      - RestAssuredApi
      - Mobiletest
      - Database
      - Mongo
      
  - name: TIPO_TEST
    displayName: 'Elija el tipo de test'
    default: cucumber   
    values:
      - cucumber
      - karate

  - name: TIPO_DRIVER
    displayName: 'Elija el tipo de driver'
    default: chrome
    values:
      - chrome
      - firefox
      - edge
      - appium

variables:
  - group: USUARIO_GENERICO
  - group: JIRA_AUTOMATIZACION
  - group: VARIABLES_TEST
  - group: SONAR2
  - group: APPIUM

stages:
  - template: serenity/init.yml@qa-pipeline-templates
    parameters:
      TIPO_TEST: ${{parameters.TIPO_TEST}}
      TIPO_DRIVER: ${{parameters.TIPO_DRIVER}}
      FLUJO: ${{parameters.FLUJO}}
      TEST_EXTRA_PARAMETERS: ""
